apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    gateway-access: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-app
  name: customer
spec:
  selector:
    matchLabels:
      app: customer  # Label selector to match pods controlled by this deployment
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: ghcr.io/sming-code/demo-app-customer-svc-worker:1.0.6
          ports:
          - containerPort: 8080
          env:
            - name: Kafka__BootstrapServers
              value: kafka-0.kafka-service.kafka.svc.cluster.local:29092
            - name: Kafka__SecurityProtocol
              value: Plaintext
            - name: ConnectionStrings__CustomersDatabase
              value: "Server=sql-server.data.svc;Database=Customer;User Id=sa;Password=LetMeIn!2;TrustServerCertificate=True;"
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-app
  name: customer
spec:
  selector:
    app: customer
  ports:
  - port: 8082
    targetPort: 8080
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: demo-app
  name: customer
spec:
  parentRefs:
  - name: gateway
    namespace: default
    sectionName: http
  hostnames:
  - "demo.sming.com"
  rules:
  - matches:
    - path:
        value: /customer
    backendRefs:
    - name: customer
      namespace: demo-app
      port: 8082
