<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="SmingCode.Utilities.Kafka" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.Kafka.MinimalConsumers" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.MinimalApi" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.Logging.AspNetCore" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.ProcessTracking" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.ProcessTracking.WebApi" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.ProcessTracking.Kafka" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.ServiceMetadata" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.ServiceMetadata.WebApplicationStartup" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.StartupProcesses" Version="1.0.33" />
    <PackageReference Include="SmingCode.Utilities.StartupProcesses.AspNetCore" Version="1.0.33" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DemoApp.Services.Travellers.Domain\DemoApp.Services.Travellers.Domain.csproj" />
    <ProjectReference Include="..\DemoApp.Services.Travellers.BusinessLogic\DemoApp.Services.Travellers.BusinessLogic.csproj" />
  </ItemGroup>

</Project>
