# @DemoApp.Services.Travellers.Api_HostAddress = http://demo.sming.com:8080/traveller/
# content-type: "application/json"

# POST {{DemoApp.Services.Travellers.Api_HostAddress}}/traveller/

# {
#     "firstName": "Test"
# }

POST http://demo.sming.com:8080/traveller HTTP/1.1
content-type: application/json

{
    "firstName": "TestFirstName",
    "surname": "TestSurname"
}

POST http://localhost:5245/traveller HTTP/1.1
content-type: application/json

{
    "firstName": "TestFirstName",
    "surname": "TestSurname"
}