name: Get Version number

on:
  workflow_call:
    inputs:
      major-version:
        type: number
        required: true
      minor-version:
        type: number
        required: true
    outputs:
      last-release-tag:
        description: The tag for the previous release
        value: ${{ jobs.get-version-no.outputs.previousTag }}
      version-no:
        description: The version number to use for this build
        value: ${{ jobs.get-version-no.outputs.nextVersionNo }}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-version-no:
    name: Get version number
    runs-on: ubuntu-latest
    outputs:
      nextVersionNo: ${{ steps.currentVersion.outputs.NEXT_VERSION }}
      previousTag: ${{ steps.currentVersion.outputs.PREVIOUS_TAG }}
    steps:
      - uses: actions/checkout@v6
      - id: currentVersion
        run: |
          latestReleaseTag="$(gh release list -L 1 --json tagName -q .[0].tagName)"
          latestReleaseTagVersionRoot=$(echo $latestReleaseTag | awk -F'.' '{ OFS="."; print $1, $2 "." }')
          latestReleaseTagBuild=$(echo $latestReleaseTag | awk -F'.' '{ print $3 }')
          newReleaseVersionRoot="v$Major_Version.$Minor_Version."
          newReleaseVersionTag=$([ "$latestReleaseTagVersionRoot" = "$newReleaseVersionRoot" ] && echo "$newReleaseVersionRoot$((latestReleaseTagBuild+1))" || echo "$newReleaseVersionRoot""0" )
          echo "PREVIOUS_TAG=$latestReleaseTag" >> $GITHUB_OUTPUT
          echo "NEXT_VERSION=${newReleaseVersionTag:1}" >> $GITHUB_OUTPUT
        env:
          Major_Version: ${{ inputs.major-version }}
          Minor_Version: ${{ inputs.minor-version }}
