name: Customer service pipeline.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  variables:
    name: Generate variables
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/get-version-no-action@v1
      id: get-version
      with:
        major: 1
        minor: 0
    - name: Display done
      run: echo "Variables loaded..."
    outputs:
      project-name-root: DemoApp.Services.Customers
      image-name-root: demo-customer-svc
      version-no: ${{ steps.get-version.outputs.version-no }}
      last-release-tag: ${{ steps.get-version.outputs.last-release-tag }}

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/build-test-action@v1

  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service-type:
          - Api
          # - Worker
    needs: [ variables, build-test ]
    steps:
    - uses: sming-code/build-docker-image-action@v1
      with:
        project-name-root: ${{ needs.variables.outputs.project-name-root }}
        image-name-root: ${{ needs.variables.outputs.image-name-root }}
        dockerfile-name-root: Dockerfile
        service-type: ${{ matrix.service-type }}
        version-number: ${{ needs.variables.outputs.version-no }}

  # create-resource-group:
  #   name: Create resource group for container app
  #   needs: [ variables, publish-docker-image ]
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   uses: ./.github/workflows/create-resource-group.yml
  #   with:
  #     container-app-name: ${{ needs.variables.outputs.image-name }}
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # deploy-to-dev:
  #   name: Deploy to dev
  #   needs: [ variables, get-version-no, build-api-docker-image, build-worker-docker-image ]
  #   steps:
  #     - deploy-worker:
  #       name: Deploy worker
  #       uses: 

  # publish-docker-image:
  #   name: Publish docker image
  #   needs: [ variables, get-version-no, build-test-create-docker-image ]
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   uses: ./.github/workflows/publish-docker-image.yml
  #   with:
  #     image-name: ${{ needs.variables.outputs.image-name }}
  #     version-number: ${{ needs.get-version-no.outputs.next-version }}
  #     archive-name: ${{ needs.build-test-create-docker-image.outputs.archive-file-name }}

  # push-to-container-app:
  #   name: Push image to container app
  #   needs: [ variables, get-version-no, create-resource-group ]
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   uses: ./.github/workflows/push-to-container-app.yml
  #   with:
  #     image-name: ${{ needs.variables.outputs.image-name }}
  #     version-number: ${{ needs.get-version-no.outputs.next-version }}
  #     resource-group: ${{ needs.create-resource-group.outputs.resource-group-id }}
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  create-release:
    name: Create release
    needs: [ variables, build-docker-images ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/add-github-release.yaml
    with:
      version-number: ${{ needs.variables.outputs.version-no }}
      previous-tag: ${{ needs.variables.outputs.last-release-tag }}