name: Push to container app

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
      version-number:
        type: string
        required: true
      resource-group:
        type: string
        required: true
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    environment: development
    name: Push image to container app
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: ca-dev-tag-customer-wrk
        resourceGroup: ${{ inputs.resource-group }}
        imageToDeploy: ghcr.io/sming-code/${{ inputs.image-name }}:${{ inputs.version-number }}
        registryUrl: ghcr.io
        registryUsername: ${{ secrets.GHCR_USERNAME }}
        registryPassword: ${{ secrets.GHCR_TOKEN }}
