name: Build and Test Worker.

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        required: true
      image-name:
        type: string
        required: true
      dockerfile-name:
        type: string
        required: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  variables:
    name: Generate variables
    runs-on: ubuntu-latest
    steps:
    - name: Display done
      run: echo "Variables loaded..."
    outputs:
      image-name: demo-customer-svc-worker
      dockerfile-name: Dockerfile.worker
      
  get-version-no:
    uses: ./.github/workflows/get-version-no.yaml

  create-resource-group:
    name: Create resource group for container app
    needs: [ variables ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/create-resource-group.yml
    with:
      container-app-name: ${{ needs.variables.outputs.image-name }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  push-to-container-app:
    name: Push image to container app
    needs: [ variables, get-version-no, create-resource-group ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/push-to-container-app.yaml
    with:
      image-name: demo-customer-svc-worker
      version-number: 1.0.2
      resource-group: rg-dev-tag
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}